
name: Build

on: [push, pull_request]

jobs:
  # Build App
  build:
    runs-on: windows-latest
    env:
      SERVICE_APP_KEY: ${{ secrets.SERVICE_APP_KEY }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Build Solution
        run: |
          cd XamarinApp/LAMA
          msbuild ./LAMA.sln /restore /p:Configuration=Debug
